PLANTS=["Apple","Bell pepper","Cassava","Cauliflower","Cherry","Chili","Citrus",
        "Coffee","Corn","Cucumber","Gauva","Grape","Jamun","Lemon","Mango","Peach",
        "Pomegranate","Potato","Rice","Soybean","Strawberry","Sugarcane",
        "Tea","Tomato","Wheat"]

PLANTS_IMGS={
 'Apple': {'cover': 'img/plants/Apple/cover.jpg',
           'plant': 'img/plants/Apple/plant.png'},
 'Bell pepper': {'cover': 'img/plants/Bell pepper/cover.jpg',
                 'plant': 'img/plants/Bell pepper/plant.png'},
 'Cassava': {'cover': 'img/plants/Cassava/cover.jpg',
             'plant': 'img/plants/Cassava/plant.png'},
 'Cauliflower': {'cover': 'img/plants/Cauliflower/cover.jpg',
                 'plant': 'img/plants/Cauliflower/plant.png'},
 'Cherry': {'cover': 'img/plants/Cherry/cover.jpg',
            'plant': 'img/plants/Cherry/plant.png'},
 'Chili': {'cover': 'img/plants/Chili/cover.jpg',
           'plant': 'img/plants/Chili/plant.png'},
 'Citrus': {'cover': 'img/plants/Citrus/cover.jpg',
            'plant': 'img/plants/Citrus/plant.png'},
 'Coffee': {'cover': 'img/plants/Coffee/cover.jpg',
            'plant': 'img/plants/Coffee/plant.png'},
 'Cucumber': {'cover': 'img/plants/Cucumber/cover.jpg',
              'plant': 'img/plants/Cucumber/plant.png'},
 'Gauva': {'cover': 'img/plants/Gauva/cover.jpg',
           'plant': 'img/plants/Gauva/plant.png'},
 'Grape': {'cover': 'img/plants/Grape/cover.jpg',
           'plant': 'img/plants/Grape/plant.png'},
 'Jamun': {'cover': 'img/plants/Jamun/cover.jpg',
           'plant': 'img/plants/Jamun/plant.png'},
 'Lemon': {'cover': 'img/plants/Lemon/cover.jpg',
           'plant': 'img/plants/Lemon/plant.png'},
 'Mango': {'cover': 'img/plants/Mango/cover.jpg',
           'plant': 'img/plants/Mango/plant.png'},
 'Peach': {'cover': 'img/plants/Peach/cover.jpg',
           'plant': 'img/plants/Peach/plant.png'},
 'Pomegranate': {'cover': 'img/plants/Pomegranate/cover.jpg',
                 'plant': 'img/plants/Pomegranate/plant.png'},
 'Potato': {'cover': 'img/plants/Potato/cover.jpg',
            'plant': 'img/plants/Potato/plant.png'},
 'Rice': {'cover': 'img/plants/Rice/cover.jpg',
          'plant': 'img/plants/Rice/plant.png'},
 'Corn': {'cover': 'img/plants/Corn/cover.jpg',
          'plant': 'img/plants/Corn/plant.png'},
 'Soybean': {'cover': 'img/plants/Soybean/cover.jpg',
             'plant': 'img/plants/Soybean/plant.png'},
 'Strawberry': {'cover': 'img/plants/Strawberry/cover.jpg',
                'plant': 'img/plants/Strawberry/plant.png'},
 'Sugarcane': {'cover': 'img/plants/Sugarcane/cover.jpg',
               'plant': 'img/plants/Sugarcane/plant.png'},
 'Tea': {'cover': 'img/plants/Tea/cover.jpg',
         'plant': 'img/plants/Tea/plant.png'},
 'Tomato': {'cover': 'img/plants/Tomato/cover.jpg',
            'plant': 'img/plants/Tomato/plant.png'},
 'Wheat': {'cover': 'img/plants/Wheat/cover.jpg',
           'plant': 'img/plants/Wheat/plant.png'}}


TEAM_MEMBERS=[{'img_url':'img/team_imgs/member-1.jpg','name':'ASKRI Aymane'},
              {'img_url':'img/team_imgs/member-2.jpg','name':'MAKAN Abdsamad'},
              {'img_url':'img/team_imgs/member-3.jpg','name':'El WANABI Idris'},
              {'img_url':'img/team_imgs/member-4.jpg','name':'ELHARRAN Ayoub'},
              {'img_url':'img/team_imgs/member-5.jpg','name':'HABOUCH Abdelmajid'},
              ]

DOCTORS=[{'img_url':'img/doctors/doctor-1.jpg','name':'Norman Borlaug','description':'American agronomist, considered the father of the Green Revolution for his work on cereal crops and his role in fighting world hunger.'},
         {'img_url':'img/doctors/doctor-2.jpg','name':'Yuan Longping','description':'Chinese agronomist, known for his work on hybrid rice cultivation and his role in fighting famine in China'},
         {'img_url':'img/doctors/doctor-3.jpg','name':'Mary-Dell Chilton','description':'American agronomist, a pioneer in plant genetics and plant biotechnology. She is known for her work on genetic transformation of plants.'},
         {'img_url':'img/doctors/doctor-4.jpg','name':'George Washington Carver','description':'American agronomist and botanist, known for his work on peanut and soybean crops'},
         {'img_url':'img/doctors/doctor-5.jpg','name':'Sir Albert Howard','description':'British agronomist, considered the father of organic agriculture for his work on composting methods and his advocacy for sustainable agricultural practices'}]